### ISSUE TITLE
For Hire

### ISSUE THREAD

**Issue by RieserStern** [bcgame-project/verify#1]
Hello.
I'm interested your game protocol as a Sr Blockchain & Full Stack developer, who has enough experience developing with Solidity, Ether, Solana, Rust, NFTs, DeFi, Web3, React/Redux, NodeJS, HTML/CSS/SCSS/BootStrap, JavaScript/TypeScript etc.
If you're interested, Plz DM me.

**Comment by Lavivinia** [comment]
Okey

**Comment by phatnguyentr** [comment]
Ok
